### ISSUE TITLE
`splitArgsAndOptions` with single argument containing `options`

### ISSUE THREAD

**Issue by Skanislav** [starknet-io/starknet.js#1252]
**Describe the bug**

```
export const splitArgsAndOptions = (args: ArgsOrCalldataWithOptions) => {
  const options = [
    'blockIdentifier',
    'parseRequest',
    'parseResponse',
    'formatResponse',
    'maxFee',
    'nonce',
    'signature',
    'addressSalt',
  ];
  const lastArg = args[args.length - 1];
  if (typeof lastArg === 'object' && options.some((x) => x in lastArg)) {
    return { args: args as ArgsOrCalldata, options: args.pop() as ContractOptions };
  }
  return { args: args as ArgsOrCalldata };
};
```

When it's called during [buildCall](https://github.com/starknet-io/starknet.js/blob/ad70b455ae108970cd739e107d9d1367372b8d52/src/contract/default.ts#L58-L67), and the contract expects a single argument which is struct with a property that overlaps this list of hardcoded options. Resulting in this:

```
Error: Invalid number of arguments, expected 1 arguments, but got 0
    at _CallData.validate (index.ts:95:13)
    at default.ts:236:23
    at getCalldata (default.ts:115:10)
    at Contract.call (default.ts:234:22)
    at Contract.get_proposal_hash (default.ts:61:21)
```

**To Reproduce**

I exported ABIs using abi-wan-kanabi for [this contracts](https://sepolia.voyager.online/contract/0x050c97a3d6ead0f7998ef29e1bbd85d3662abd152016406ee1cb2d37d156fdb5#readContract) and tried to call the `get_proposal_hash`. I spotted the error because the similar call worked for the function `encode_proposal_data` that accepts two arguments and works just fine. 

**Expected behavior**
- 

**Desktop (please complete the following information):**

- Browser & version Chrome Version 124.0.6367.208
- Node version v20.14.0
- Starknet.js version 6.17.0
- Network devnet

**Comment by penovicp** [comment]
It looks like it should be doable to refactor `splitArgsAndOptions` to accept and use the corresponding ABI information to discern if the options object is used rather than through duck typing. The only snag is that the possible inputs are fairly flexible with allowing both structured and precompiled values so extra care needs to be taken to cover all the scenarios.

If this is a major blocker for you there is a silver lining in the aforementioned flexibility in that using the output of [CallData.compile(...)](http://starknetjs.com/docs/API/classes/CallData) for the method input or some other approach from the [docs](https://starknetjs.com/docs/guides/interact) can be used as a workaround.

**Comment by poolcleaner6** [comment]
Perhaps `splitArgsAndOptions` could include a check for the expected argument type from the ABI. This could help avoid errors when the contract expects a single struct with properties that overlap with options

**Comment by PhilippeR26** [comment]
Closing: fixed by #1255 and released in v7.0.0. `splitArgsAndOptions` no longer exists. Call options are now passed only through `contract.withOptions(...)`, so a struct argument whose fields share a name with an option is passed through as a regular argument. The issue simply wasn't auto-closed because the fix landed on the v7 beta branch.
